{% set name = "jsontableschema-pandas" %}
{% set version = "0.5.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "cf5833ebe4ddcab29f3c652304aff6a4316fa9b92d52d9ee047b9cffbb18cebf" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six >=1.9,<2.0
    - pandas >=0.18,<2.0
    - tabulator-py >=0.7,<2.0
    - jsontableschema >=0.7,<2.0

test:
  imports:
    - jsontableschema_pandas

about:
  home: https://github.com/frictionlessdata/jsontableschema-pandas-py
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  license_family: LGPL
  license: LGPLv3
  summary: 'Generate Pandas data frames, load and extract data, based on JSON Table Schema descriptors.'
  dev_url: https://github.com/frictionlessdata/jsontableschema-pandas-py

extra:
  recipe-maintainers:
    - pmlandwehr
