travis:
  secure:
    BINSTAR_TOKEN: kjHNsynEMbWLsx8Cv+5OVDAgJhChDCqxLZwXyHcliVEgLqLJRnm5g4JeOOn3mVb884I9Oe6E+DCa3+qpXuMT0FIKGpRVTZZa/5V2CPpPpgCHIEfkwjr/TPTV5/b8Cw4ctcHc3bIN6gHJHVFo16HBTH6cKikjwIddKBd8wAxaUIIJCBQSnmlxUAckGs2enZyoXuVTbz0SEch2LoDbWAAMnWQNn/FrX54WXhh+EnDkj393CQoyeWbX1AzfT6ZNjK/j3DEZTmXspEa7pylrvByhGJ52y8vL+KMaK+loH5VF/PN7P5Un1wMJCgR7fT3bRu1s1Kx1GKlqc1hZ4KyKok9zS9URWcZRLXr1TjaW05FY2ccX1IDU50jT+nzZTtnq71/Lfh/QDLxIrL7MQ+j8flTykt6nFs6X+wnlRe758BYm43CKifGq3vPhTQiBeRQEuqN3OFNZ8Qh5EhcgWHmSOWfZ9OgFDyNZCqsVCcjThaiJ9q44EtPvfegyjZpsDIWuomadgTMYrOXIhtizfTJl50vDYKlNl2cOj0Hg2ATTFD2h9Lh3/21dLpoMueh3bDiGg2hMkJZKnY6XVDLvWfBS25lg8eWmlvjhdGY3v99ZAidNun1TDnd3oZJu97bK+sLJirn93nMBOblvzAvFzgVO29nJ50EramWnbq4FifqVwyCr7CA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
