travis:
  secure:
    BINSTAR_TOKEN: LZTpiQuF3qUHhq7fPX3t/bdJpEQefXwMKkq+vkMlRVoeMNJ/9yJhZiw16FcvO3+PIUVYETwe6RsSus1q4p3xa1wYlbqvm+Hs0DdAj9I2Kf7jTg+qrv7qZpawCzK3i7rh0wdBh6julda/m4iUDu33+lXLp6yBP5OCAhHJTsD3OPtsxa/GxhZd054He3pKg+CU00JtEY7MqvJ2W98b3CZPrbHvB98pzrvB54NfDElGtyOJJhobniqz29VGS9CKhmlM3XIL3+Uf3enUCyqRqXayRtvgX9ceacuVbLqvMbJS+KEMA2eNlv1zJAkL7hiGPA3CM5QUh93jIMWiZ3jBElwenmUXd8EuQfgjFRsAAWAOcI4ni0dZAT48QP3AQ+/qV73zp5hLSYgUKjJhLFNJJ18IWIChuoIbrW2Cx1t00SuoVhP5Ft1Q9ld9wyZQafucb3jpLttKpkMhwYcxAhqEAgEqEU5QIwrpaLZHWrQtwV8hlpm32aWRDv3jsetZRiMLTW9ddXlLxI4Fc0+nLkgtPy96YizX76OvjZsskm7vGT56cbbzApyFe+M/Tgl+kMEsABuaMsyeTQ8MIC3Yv2HHGYISQvm3jy+zvIdPbWdHnPSwmnuxidExCQqQIbhA7T0l3psRYOK4hnXjbWpORQn+/TKsWVsc6Y/a3vTovSMvelqhbxE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
